/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as CompanyStacksRouteImport } from './routes/company-stacks'
import { Route as CommunityStacksRouteImport } from './routes/community-stacks'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksUserUsernameRouteImport } from './routes/stacks/user.$username'
import { Route as StacksCompanySlugRouteImport } from './routes/stacks/company.$slug'
import { Route as StacksUserUsernameIndexRouteImport } from './routes/stacks/user.$username.index'
import { Route as StacksCompanySlugIndexRouteImport } from './routes/stacks/company.$slug.index'
import { Route as StacksUserUsernameEditRouteImport } from './routes/stacks/user.$username.edit'
import { Route as StacksCompanySlugEditRouteImport } from './routes/stacks/company.$slug.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyStacksRoute = CompanyStacksRouteImport.update({
  id: '/company-stacks',
  path: '/company-stacks',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityStacksRoute = CommunityStacksRouteImport.update({
  id: '/community-stacks',
  path: '/community-stacks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksUserUsernameRoute = StacksUserUsernameRouteImport.update({
  id: '/stacks/user/$username',
  path: '/stacks/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksCompanySlugRoute = StacksCompanySlugRouteImport.update({
  id: '/stacks/company/$slug',
  path: '/stacks/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksUserUsernameIndexRoute = StacksUserUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StacksUserUsernameRoute,
} as any)
const StacksCompanySlugIndexRoute = StacksCompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StacksCompanySlugRoute,
} as any)
const StacksUserUsernameEditRoute = StacksUserUsernameEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StacksUserUsernameRoute,
} as any)
const StacksCompanySlugEditRoute = StacksCompanySlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StacksCompanySlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/community-stacks': typeof CommunityStacksRoute
  '/company-stacks': typeof CompanyStacksRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/stacks/company/$slug': typeof StacksCompanySlugRouteWithChildren
  '/stacks/user/$username': typeof StacksUserUsernameRouteWithChildren
  '/stacks/company/$slug/edit': typeof StacksCompanySlugEditRoute
  '/stacks/user/$username/edit': typeof StacksUserUsernameEditRoute
  '/stacks/company/$slug/': typeof StacksCompanySlugIndexRoute
  '/stacks/user/$username/': typeof StacksUserUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/community-stacks': typeof CommunityStacksRoute
  '/company-stacks': typeof CompanyStacksRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/stacks/company/$slug/edit': typeof StacksCompanySlugEditRoute
  '/stacks/user/$username/edit': typeof StacksUserUsernameEditRoute
  '/stacks/company/$slug': typeof StacksCompanySlugIndexRoute
  '/stacks/user/$username': typeof StacksUserUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/community-stacks': typeof CommunityStacksRoute
  '/company-stacks': typeof CompanyStacksRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/stacks/company/$slug': typeof StacksCompanySlugRouteWithChildren
  '/stacks/user/$username': typeof StacksUserUsernameRouteWithChildren
  '/stacks/company/$slug/edit': typeof StacksCompanySlugEditRoute
  '/stacks/user/$username/edit': typeof StacksUserUsernameEditRoute
  '/stacks/company/$slug/': typeof StacksCompanySlugIndexRoute
  '/stacks/user/$username/': typeof StacksUserUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/community-stacks'
    | '/company-stacks'
    | '/imprint'
    | '/privacy'
    | '/terms'
    | '/stacks/company/$slug'
    | '/stacks/user/$username'
    | '/stacks/company/$slug/edit'
    | '/stacks/user/$username/edit'
    | '/stacks/company/$slug/'
    | '/stacks/user/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/community-stacks'
    | '/company-stacks'
    | '/imprint'
    | '/privacy'
    | '/terms'
    | '/stacks/company/$slug/edit'
    | '/stacks/user/$username/edit'
    | '/stacks/company/$slug'
    | '/stacks/user/$username'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/community-stacks'
    | '/company-stacks'
    | '/imprint'
    | '/privacy'
    | '/terms'
    | '/stacks/company/$slug'
    | '/stacks/user/$username'
    | '/stacks/company/$slug/edit'
    | '/stacks/user/$username/edit'
    | '/stacks/company/$slug/'
    | '/stacks/user/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CommunityStacksRoute: typeof CommunityStacksRoute
  CompanyStacksRoute: typeof CompanyStacksRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  StacksCompanySlugRoute: typeof StacksCompanySlugRouteWithChildren
  StacksUserUsernameRoute: typeof StacksUserUsernameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-stacks': {
      id: '/company-stacks'
      path: '/company-stacks'
      fullPath: '/company-stacks'
      preLoaderRoute: typeof CompanyStacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-stacks': {
      id: '/community-stacks'
      path: '/community-stacks'
      fullPath: '/community-stacks'
      preLoaderRoute: typeof CommunityStacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/user/$username': {
      id: '/stacks/user/$username'
      path: '/stacks/user/$username'
      fullPath: '/stacks/user/$username'
      preLoaderRoute: typeof StacksUserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/company/$slug': {
      id: '/stacks/company/$slug'
      path: '/stacks/company/$slug'
      fullPath: '/stacks/company/$slug'
      preLoaderRoute: typeof StacksCompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/user/$username/': {
      id: '/stacks/user/$username/'
      path: '/'
      fullPath: '/stacks/user/$username/'
      preLoaderRoute: typeof StacksUserUsernameIndexRouteImport
      parentRoute: typeof StacksUserUsernameRoute
    }
    '/stacks/company/$slug/': {
      id: '/stacks/company/$slug/'
      path: '/'
      fullPath: '/stacks/company/$slug/'
      preLoaderRoute: typeof StacksCompanySlugIndexRouteImport
      parentRoute: typeof StacksCompanySlugRoute
    }
    '/stacks/user/$username/edit': {
      id: '/stacks/user/$username/edit'
      path: '/edit'
      fullPath: '/stacks/user/$username/edit'
      preLoaderRoute: typeof StacksUserUsernameEditRouteImport
      parentRoute: typeof StacksUserUsernameRoute
    }
    '/stacks/company/$slug/edit': {
      id: '/stacks/company/$slug/edit'
      path: '/edit'
      fullPath: '/stacks/company/$slug/edit'
      preLoaderRoute: typeof StacksCompanySlugEditRouteImport
      parentRoute: typeof StacksCompanySlugRoute
    }
  }
}

interface StacksCompanySlugRouteChildren {
  StacksCompanySlugEditRoute: typeof StacksCompanySlugEditRoute
  StacksCompanySlugIndexRoute: typeof StacksCompanySlugIndexRoute
}

const StacksCompanySlugRouteChildren: StacksCompanySlugRouteChildren = {
  StacksCompanySlugEditRoute: StacksCompanySlugEditRoute,
  StacksCompanySlugIndexRoute: StacksCompanySlugIndexRoute,
}

const StacksCompanySlugRouteWithChildren =
  StacksCompanySlugRoute._addFileChildren(StacksCompanySlugRouteChildren)

interface StacksUserUsernameRouteChildren {
  StacksUserUsernameEditRoute: typeof StacksUserUsernameEditRoute
  StacksUserUsernameIndexRoute: typeof StacksUserUsernameIndexRoute
}

const StacksUserUsernameRouteChildren: StacksUserUsernameRouteChildren = {
  StacksUserUsernameEditRoute: StacksUserUsernameEditRoute,
  StacksUserUsernameIndexRoute: StacksUserUsernameIndexRoute,
}

const StacksUserUsernameRouteWithChildren =
  StacksUserUsernameRoute._addFileChildren(StacksUserUsernameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CommunityStacksRoute: CommunityStacksRoute,
  CompanyStacksRoute: CompanyStacksRoute,
  ImprintRoute: ImprintRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  StacksCompanySlugRoute: StacksCompanySlugRouteWithChildren,
  StacksUserUsernameRoute: StacksUserUsernameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
